apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-react-example
  namespace: production
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  rules:
    - host: spring.demo.tahmid.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-react-example
                port:
                  number: 80
