apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - secrets.yaml
  - service.yaml
commonLabels:
  app: go-example
  environment: production
images:
  - name: docker.io/tahminator/go-example
    newTag: latest
