apiVersion: v1
kind: Service
metadata:
  name: postgres-public
  namespace: production
spec:
  type: LoadBalancer
  selector:
    cnpg.io/cluster: postgres-shared
    cnpg.io/instanceRole: primary
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
