apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - quota.yaml
  - ./instalock-app
  - ./postgres
  - ./instalock-cron
  - ./spring-react-example
  - ./go-example
  - ./redis
