apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - secrets.yaml
  - service.yaml
  - monitor.yaml
commonLabels:
  app: instalock-web
  environment: production
images:
  - name: docker.io/tahminator/instalock-web
    newTag: latest
