apiVersion: v1
kind: Service
metadata:
  name: instalock-web
  namespace: production
spec:
  selector:
    app: instalock-web
  ports:
    - name: http-web
      protocol: TCP
      port: 80
      targetPort: 3050
